export const FETCH_FILES_REQUEST = "FETCH_FILES_REQUEST";
export const FETCH_FILES_SUCCESS = "FETCH_FILES_SUCCESS";
export const FETCH_FILES_FAILURE = "FETCH_FILES_FAILURE";
export const SET_SELECTED_EXTENSIONS = "SET_SELECTED_EXTENSIONS";
export const TOGGLE_SHOW_ALL_FILES = "TOGGLE_SHOW_ALL_FILES";
export const SET_SELECTED_FILES = "SET_SELECTED_FILES";
export const SET_ANALYSIS_RESULTS = "SET_ANALYSIS_RESULTS";
export const SET_EXPANDED_ACCORDION_ID = "SET_EXPANDED_ACCORDION_ID";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
